### PR TITLE
Ui redesign

### PR DESCRIPTION
**Pull request by osamasalahuddin**
@shoaib333 Kindly review the changes and merge them to the main branch if no bug is found

### CODE REVIEW

**Comment by shoaib333** [comment]
@osamasalahuddin I will review the changes shortly, could you please complete the settings and alarm notification as well so that I can review the full changes at once.

**Comment by osamasalahuddin** [comment]
@shoaib333 The design of Settings and AlarmNotifications is not present. I dont know what to implement in those screens and what will be the layout in them. If you could update the design of these screens on Trello then I will add them as well

**Comment by shoaib333** [comment]
@osamasalahuddin I believe all the design was completed, however I will check that and update if it is missing.
PS: by AlarmNotification you mean the reminders app will send to the user regarding maintenance and other activities?

**Comment by osamasalahuddin** [comment]
@shoaib333 probably yes I couldn't quite remember why this option was present in the UI design. But I think that was regarding the ones that you have described.
Also add the layout of the settings screen as well

**Comment by shoaib333** [comment]
@osamasalahuddin I have reviewed the changes, some bugs fixing and correction is required before we can merged this branch with master.

-on login screen, There cancel button should minimize the application or close it, or we can remove the "Cancel" button from the login as it is currently doing nothing.
-"Cancel" button on Signup page is also not working, it is suppose to take you back to the sign in page
-I have failed to signup. i.e. sign up is also not working, I tried to enter as much information as much it is showing. 

last but not the least, kindly remove the message envelope icon from the app, as it is doing no work in the app.

Kindly make the following changes so that we can merge it with the master.

**Comment by shoaib333** [comment]
UI now looks fine and a bit more classical or old school :). thumbs up for that. :+1:  good work @osamasalahuddin

**Comment by osamasalahuddin** [comment]
@shoaib333 merge this branch into the main branch otherwise merging issues will appear in the subsequent commits.

Following fixes will be done:
-Removal of the floating action bar (email) button from the app
-Cancel button implementation will be added into the login and sign up screen
-The signup issue is not related to UI redesign. It is a functionality issue and will be dealt with in the other branch this one is just for UI.

Kindly merge this and then I will move forward with the bugs

**Pull request merged**
